<?php

namespace Assegai\Core\Enumerations;

enum EventChannel: string
{
  case APP_INIT_START = 'APP_INIT_START';
  case APP_INIT_FINISH = 'APP_INIT_FINISH';
  case APP_LISTENING_START = 'APP_LISTENING_START';
  case APP_LISTENING_FINISH = 'APP_LISTENING_FINISH';
  case APP_SHUTDOWN_START = 'APP_SHUTDOWN_START';
  case APP_SHUTDOWN_FINISH = 'APP_SHUTDOWN_FINISH';
  case MODULE_RESOLUTION_START = 'MODULE_RESOLUTION_START';
  case MODULE_RESOLUTION_FINISH = 'MODULE_RESOLUTION_FINISH';
  case PROVIDER_RESOLUTION_START = 'PROVIDER_RESOLUTION_START';
  case PROVIDER_RESOLUTION_FINISH = 'PROVIDER_RESOLUTION_FINISH';
  case CONTROLLER_RESOLUTION_START = 'CONTROLLER_RESOLUTION_START';
  case CONTROLLER_RESOLUTION_FINISH = 'CONTROLLER_RESOLUTION_FINISH';
  case CONTROLLER_WILL_ACTIVATE = 'CONTROLLER_WILL_ACTIVATE';
  case CONTROLLER_DID_ACTIVATE = 'CONTROLLER_DID_ACTIVATE';
  case HANDLER_WILL_ACTIVATE = 'HANDLER_WILL_ACTIVATE';
  case HANDLER_DID_ACTIVATE = 'HANDLER_DID_ACTIVATE';
  case REQUEST_HANDLING_START = 'REQUEST_HANDLING_START';
  case REQUEST_HANDLING_FINISH = 'REQUEST_HANDLING_FINISH';
  case RESPONSE_HANDLING_START = 'RESPONSE_HANDLING_START';
  case RESPONSE_HANDLING_FINISH = 'RESPONSE_HANDLING_FINISH';
  case SESSION_START = 'SESSION_START';
}